@echo off
set MATLAB=C:\Program Files\MATLAB\R2017b
"%MATLAB%\bin\win64\gmake" -f just_the_dynamics1.mk  ISPROTECTINGMODEL=NOTPROTECTING RSIM_SOLVER_SELECTION=2 OPTS="-DSLMSG_ALLOW_SYSTEM_ALLOC -DTGTCONN -DON_TARGET_WAIT_FOR_START=0"
